# Generated by Django 5.2.4 on 2025-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
            ],
            options={
                'db_table': 'EVENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('pk', models.CompositePrimaryKey('event', 'user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('subscription_date', models.DateTimeField(blank=True, null=True)),
                ('participants', models.IntegerField()),
            ],
            options={
                'db_table': 'EVENT_SUBSCRIPTION',
                'managed': False,
            },
        ),
    ]
