# Generated by Django 5.2.4 on 2025-09-30 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'BOOKING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('pk', models.CompositePrimaryKey('booking', 'service', blank=True, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('people', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Booking detail',
                'verbose_name_plural': 'Booking details',
                'db_table': 'BOOKING_DETAIL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('ROOM', 'Room')], max_length=20)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'SERVICE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('service', models.OneToOneField(db_column='service', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='restaurant', serialize=False, to='service.service')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('max_capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'RESTAURANT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('service', models.OneToOneField(db_column='service', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='room', serialize=False, to='service.service')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('max_capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'ROOM',
                'managed': False,
            },
        ),
    ]
