# Generated by Django 5.2.4 on 2025-09-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'RESERVATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationDetail',
            fields=[
                ('pk', models.CompositePrimaryKey('reservation', 'service', blank=True, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('people', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reservation detail',
                'verbose_name_plural': 'Reservation details',
                'db_table': 'RESERVATION_DETAIL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('POOL', 'Pool'), ('PLAYGROUND', 'Playground'), ('ROOM', 'Room')], max_length=20)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'SERVICE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('service', models.OneToOneField(db_column='service', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='restaurant', serialize=False, to='service.service')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('max_capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'RESTAURANT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('service', models.OneToOneField(db_column='service', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='room', serialize=False, to='service.service')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('max_capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'ROOM',
                'managed': False,
            },
        ),
    ]
