# Generated by Django 5.2.4 on 2025-09-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_restaurant_room_alter_service_service_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reservationdetail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False},
        ),
    ]
