# Generated by Django 5.2.4 on 2025-09-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='RESERVATION',
        ),
        migrations.AlterModelTable(
            name='reservationdetail',
            table='RESERVATION_DETAIL',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='RESTAURANT',
        ),
        migrations.AlterModelTable(
            name='room',
            table='ROOM',
        ),
        migrations.AlterModelTable(
            name='service',
            table='SERVICE',
        ),
    ]
