# Generated by Django 5.2.4 on 2025-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeServiceNow',
            fields=[
                ('service_id', models.IntegerField(db_column='service_id', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=50, null=True)),
                ('restaurant_code', models.CharField(db_column='restaurant_code', max_length=64, null=True)),
                ('room_code', models.CharField(db_column='room_code', max_length=64, null=True)),
                ('restaurant_max_capacity', models.IntegerField(db_column='restaurant_max_capacity', null=True)),
                ('room_max_capacity', models.IntegerField(db_column='room_max_capacity', null=True)),
                ('people_booked_now', models.IntegerField(db_column='people_booked_now', null=True)),
                ('reservations_now', models.IntegerField(db_column='reservations_now', null=True)),
                ('available', models.BooleanField(db_column='available', null=True)),
                ('available_seats', models.IntegerField(db_column='available_seats', null=True)),
            ],
            options={
                'db_table': 'free_services_now',
                'ordering': ['-available', 'type', 'service_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FullyBookedEvent',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255, null=True)),
                ('event_date', models.DateTimeField(db_column='event_date', null=True)),
                ('seats', models.IntegerField(db_column='seats', null=True)),
                ('total_participants', models.IntegerField(db_column='total_participants', null=True)),
            ],
            options={
                'db_table': 'fully_booked_events',
                'ordering': ['-event_date'],
                'managed': False,
            },
        ),
    ]
