# Generated by Django 5.2.4 on 2025-09-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEmployee',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'active_employees',
                'managed': False,
            },
        ),
    ]
