# Generated by Django 5.2.4 on 2025-09-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_freeservicenow_fullybookedevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeservicenow',
            options={'managed': False},
        ),
    ]
